sudo: required

services:
  - docker

before_install:
  - docker build -t rbuckland/chromium-page-saver chromium-page-saver/

script:
  - docker run -ti -v `pwd`:/x --rm rbuckland/chromium-page-saver https://github.com github.png

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push rbuckland/chromium-page-saver;
    fi
