FROM rbuckland/chromium-page-saver:latest

# https://github.com/jgraph/mxgraph/issues/83
# specifically a pain. 
# RUN npm install mxgraph
RUN npm install --save git+https://github.com/NicCOConnor/mxgraph.git
# RUN npm install --save git+https://github.com/jgraph/mxgraph.git
